### ISSUE TITLE
Remove experimentation table preventing wrong clicks(i'll try a PR) 

### ISSUE THREAD

**Issue by satyamedh** [bowser0000/SkyblockMod#88] opened 2021-03-27 04:40 UTC
Removing the feature that prevents clicking the wrong tile on the experimentation table

imma try a PR but not sure

**Comment by satyamedh** [comment] 2021-03-27 04:41
btw this is to comply with the new mod conditions

**Comment by bowser0000** [comment] 2021-04-03 01:25
Duplicate of #87

**Closed by bowser0000** 2021-04-03 01:25 UTC
